name = "wildebeest"
main = "src/index.ts"
compatibility_date = "2022-12-05"
workers_dev = true

[[d1_databases]]
binding = "DATABASE"
database_name = "wildebeest"
database_id = "83821907-97fd-44b4-8f21-e3d6b736e7ef"
